### ISSUE TITLE
How to access the image to be tested from the Android emulator

### ISSUE THREAD

**Issue by PhilippeComte** [matt-ny/rscnn#6]
Hello , 
Many thanks for sharing this demo app. 
I've installed the app on the Android Studio , launched the emulator , launched the app.
I now want to select a file to test the model but I can't find a way to do that . 

<img width="397" alt="image" src="https://user-images.githubusercontent.com/7049461/86236061-bb995500-bb99-11ea-80b9-873e502f0cbc.png">

<img width="493" alt="image" src="https://user-images.githubusercontent.com/7049461/86235818-52b1dd00-bb99-11ea-86ff-22f8ba16e14b.png">

(I understand that i need to access  folder images / testimages  where there are some lego pictures.
Can you help ? 
Thank you very much

**Comment by PhilippeComte** [comment]
Hello , I've managed to import some photos but  not to access the images / testimages folder .

**Comment by matt-ny** [comment]
Thanks for your question @PhilippeComte !

I've found these steps to be good for getting images into the gallery of the device emulator:

https://www.youtube.com/watch?v=xWqzdtPLvBE

Just select the images from your workstation's disk from the images/testimages folder for the upload.

Alternatively, you could use these steps where you drag and drop the images into the emulator window, then take some additional steps to set up the virtual SD card:

https://stackoverflow.com/a/38736733/6441660

Keep in mind, what you are doing is copying the image data from your laptop's disk into the emulator.  You cannot directly access the laptop's disk from the code running in the emulator.  If this answers your question, please close the issue.

**Comment by PhilippeComte** [comment]
Thank you matt @matt-ny !
